-- Generated by flyway quarkus extension at 2025-02-28
    create table contact_information (
        id bigint generated by default as identity,
        profile_id bigint not null,
        type varchar(255) not null,
        value varchar(255) not null,
        primary key (id)
    );

    create table menu_items (
        price integer not null,
        id bigint generated by default as identity,
        restaurant_id bigint not null,
        description varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table order_items (
        quantity integer not null,
        id bigint generated by default as identity,
        menu_item_id bigint not null,
        primary key (id)
    );

    create table orders (
        state smallint not null check (state between 0 and 3),
        id bigint generated by default as identity,
        profile_id bigint not null,
        primary key (id)
    );

    create table orders_order_items (
        Order_id bigint not null,
        items_id bigint not null unique
    );

    create table profiles (
        id bigint generated by default as identity,
        displayName varchar(255) not null,
        name varchar(255) not null unique,
        primaryEmail varchar(255) not null unique,
        profilePictureUrl varchar(255),
        primary key (id)
    );

    create table restaurants (
        id bigint generated by default as identity,
        address_city varchar(255) not null,
        address_county varchar(255) not null,
        address_postal_code varchar(255) not null,
        address_street varchar(255) not null,
        displayName varchar(255) not null,
        primary key (id)
    );

    create table sessions (
        deadline timestamp(6) not null,
        id bigint generated by default as identity,
        organizer_id bigint unique,
        restaurant_id bigint unique,
        primary key (id)
    );

    create table sessions_orders (
        Session_id bigint not null,
        orders_id bigint not null unique
    );

    alter table if exists contact_information 
       add constraint FKhv23s561adw5470k6nwrnai6w 
       foreign key (profile_id) 
       references profiles;

    alter table if exists menu_items 
       add constraint FKhaqtoboitpl0n541y0sc753my 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists order_items 
       add constraint FKdtfg1f49yr5yye2fpl2xid2xo 
       foreign key (menu_item_id) 
       references menu_items;

    alter table if exists orders 
       add constraint FKeieprmmaadhys18lur996ikv4 
       foreign key (profile_id) 
       references profiles;

    alter table if exists orders_order_items 
       add constraint FKjyll3gu3l9d1ekgurrr5xk5ee 
       foreign key (items_id) 
       references order_items;

    alter table if exists orders_order_items 
       add constraint FK15wm72fk6w2lvwketp3u1u4f5 
       foreign key (Order_id) 
       references orders;

    alter table if exists sessions 
       add constraint FKbuw0c0aj6x4hh884ig4830rpu 
       foreign key (organizer_id) 
       references profiles;

    alter table if exists sessions 
       add constraint FK3xj60qc0om6hdajtyb5b5x35i 
       foreign key (restaurant_id) 
       references restaurants;

    alter table if exists sessions_orders 
       add constraint FKhjb762h861fjoxe7jp3b7ersb 
       foreign key (orders_id) 
       references orders;

    alter table if exists sessions_orders 
       add constraint FKo7v0eal5fglw755wbtlrnfbi0 
       foreign key (Session_id) 
       references sessions;
