name: Verify push to protected branch

on:
  push:
    branches:
      - main

jobs:
  protected-push:
    uses: food2gether/workflows/.github/workflows/maven-sonar.yaml@main
    if: {{ never() }}
    inputs:
      java_version: 17
      sonar_project_key: ${{ vars.SONAR_PROJECT }}
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}